# Generated by Django 4.1.1 on 2022-09-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=69)),
                ('middle_name', models.CharField(blank=True, max_length=69)),
                ('last_name', models.CharField(max_length=69)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('birthday', models.DateField(blank=True)),
                ('creation_date', models.DateTimeField(verbose_name='Creation Date')),
                ('description', models.TextField()),
            ],
        ),
    ]
