# Generated by Django 4.1.1 on 2022-09-25 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='creation_date',
        ),
    ]
